---
kind: Secret
apiVersion: v1
metadata:
  name: "db-secret"
  labels:
    app.kubernetes.io/name: trusti
data:
  username: "user"
  password: "password"
type: Opaque
---
kind: Service
apiVersion: v1
metadata:
  name: "db-service"
  labels:
    app.kubernetes.io/name: trusti
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: "db"
  type: ClusterIP
  sessionAffinity: None
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: "db-deployment"
  labels:
    app.kubernetes.io/name: trusti
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "db"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "db"
    spec:
      volumes:
        - name: postgresql-data
          emptyDir: { }
      containers:
        - name: "db"
          image: "registry.access.redhat.com/rhscl/postgresql-10-rhel7:1"
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: "db-secret"
                  key: username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: POSTGRESQL_DATABASE
              value: trusti
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "10m"
              memory: "64Mi"
          livenessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - 'psql -U $POSTGRESQL_USER -d $POSTGRESQL_DATABASE -c ''SELECT 1'' '
            initialDelaySeconds: 20
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - 'psql -U $POSTGRESQL_USER -d $POSTGRESQL_DATABASE -c ''SELECT 1'' '
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: postgresql-data
              mountPath: "/var/lib/postgresql"
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: { }
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600