package org.trusti.global.quarkus;

import io.quarkus.runtime.annotations.RegisterForReflection;
import schemas.csaf.*;
import schemas.cve.v5.CveV5;
import schemas.cve.v5.tags.AdpTags;
import schemas.cve.v5.tags.CnaTags;
import schemas.cve.v5.tags.ReferenceTags;
import schemas.osv.*;
import schemas.osv.Package;

@RegisterForReflection(
        serialization = true,
        registerFullHierarchy = true,
        targets = {
                Csaf.class,
                AcknowledgmentsT.class,
                AggregateSeverity.class,
                BranchesT.class,
                BranchesT.Category.class,
                CvssV20.class,
                CvssV20.AccessComplexityType.class,
                CvssV20.AccessVectorType.class,
                CvssV20.AuthenticationType.class,
                CvssV20.CiaRequirementType.class,
                CvssV20.CiaType.class,
                CvssV20.CollateralDamagePotentialType.class,
                CvssV20.ExploitabilityType.class,
                CvssV20.RemediationLevelType.class,
                CvssV20.ReportConfidenceType.class,
                CvssV20.TargetDistributionType.class,
                CvssV20.Version.class,
                Cwe.class,
                Distribution.class,
                Document.class,
                Document.CsafVersion.class,
                Engine.class,
                FileHash.class,
                Flag.class,
                Flag.Label.class,
                FullProductNameT.class,
                Generator.class,
                Hash.class,
                Id.class,
                Involvement.class,
                Involvement.Status.class,
                Involvement.Party.class,
                NotesT.class,
                NotesT.Category.class,
                ProductGroup.class,
                ProductIdentificationHelper.class,
                ProductStatus.class,
                ProductTree.class,
                Publisher.class,
                Publisher.Category.class,
                ReferencesT.class,
                ReferencesT.Category.class,
                Relationship.class,
                Relationship.Category.class,
                Remediation.class,
                Remediation.Category.class,
                RestartRequired.class,
                RestartRequired.Category.class,
                RevisionHistory.class,
                Score.class,
                Thread.class,
                Thread.State.class,
                Thread.UncaughtExceptionHandler.class,
                Tlp.class,
                Tlp.Label.class,
                Tracking.class,
                Tracking.Status.class,
                Vulnerability.class,
                XGenericUri.class,

                Osv.class,
                Affected.class,
                Credit.class,
                Credit.Type.class,
                DatabaseSpecific.class,
                DatabaseSpecific__1.class,
                DatabaseSpecific__2.class,
                EcosystemSpecific.class,
                Event.class,
                Package.class,
                Range.class,
                Range.Type.class,
                Reference.class,
                Reference.Type.class,
                Severity.class,
                Severity.Type.class,

                CveV5.class,
                schemas.cve.v5.imports.cvss.CvssV20.class,
                schemas.cve.v5.imports.cvss.CvssV20.AccessComplexityType.class,
                schemas.cve.v5.imports.cvss.CvssV20.AccessVectorType.class,
                schemas.cve.v5.imports.cvss.CvssV20.AuthenticationType.class,
                schemas.cve.v5.imports.cvss.CvssV20.CiaRequirementType.class,
                schemas.cve.v5.imports.cvss.CvssV20.CiaType.class,
                schemas.cve.v5.imports.cvss.CvssV20.CollateralDamagePotentialType.class,
                schemas.cve.v5.imports.cvss.CvssV20.ExploitabilityType.class,
                schemas.cve.v5.imports.cvss.CvssV20.RemediationLevelType.class,
                schemas.cve.v5.imports.cvss.CvssV20.ReportConfidenceType.class,
                schemas.cve.v5.imports.cvss.CvssV20.TargetDistributionType.class,
                schemas.cve.v5.imports.cvss.CvssV20.Version.class,
                schemas.cve.v5.imports.cvss.CvssV30.class,
                schemas.cve.v5.imports.cvss.CvssV30.AttackComplexityType.class,
                schemas.cve.v5.imports.cvss.CvssV30.AttackVectorType.class,
                schemas.cve.v5.imports.cvss.CvssV30.CiaRequirementType.class,
                schemas.cve.v5.imports.cvss.CvssV30.CiaType.class,
                schemas.cve.v5.imports.cvss.CvssV30.ConfidenceType.class,
                schemas.cve.v5.imports.cvss.CvssV30.ExploitCodeMaturityType.class,
                schemas.cve.v5.imports.cvss.CvssV30.ModifiedAttackComplexityType.class,
                schemas.cve.v5.imports.cvss.CvssV30.ModifiedAttackVectorType.class,
                schemas.cve.v5.imports.cvss.CvssV30.ModifiedCiaType.class,
                schemas.cve.v5.imports.cvss.CvssV30.ModifiedPrivilegesRequiredType.class,
                schemas.cve.v5.imports.cvss.CvssV30.ModifiedScopeType.class,
                schemas.cve.v5.imports.cvss.CvssV30.ModifiedUserInteractionType.class,
                schemas.cve.v5.imports.cvss.CvssV30.PrivilegesRequiredType.class,
                schemas.cve.v5.imports.cvss.CvssV30.RemediationLevelType.class,
                schemas.cve.v5.imports.cvss.CvssV30.ScopeType.class,
                schemas.cve.v5.imports.cvss.CvssV30.SeverityType.class,
                schemas.cve.v5.imports.cvss.CvssV30.UserInteractionType.class,
                schemas.cve.v5.imports.cvss.CvssV30.Version.class,
                schemas.cve.v5.imports.cvss.CvssV31.class,
                schemas.cve.v5.imports.cvss.CvssV31.AttackComplexityType.class,
                schemas.cve.v5.imports.cvss.CvssV31.AttackVectorType.class,
                schemas.cve.v5.imports.cvss.CvssV31.CiaRequirementType.class,
                schemas.cve.v5.imports.cvss.CvssV31.CiaType.class,
                schemas.cve.v5.imports.cvss.CvssV31.ConfidenceType.class,
                schemas.cve.v5.imports.cvss.CvssV31.ExploitCodeMaturityType.class,
                schemas.cve.v5.imports.cvss.CvssV31.ModifiedAttackComplexityType.class,
                schemas.cve.v5.imports.cvss.CvssV31.ModifiedAttackVectorType.class,
                schemas.cve.v5.imports.cvss.CvssV31.ModifiedCiaType.class,
                schemas.cve.v5.imports.cvss.CvssV31.ModifiedPrivilegesRequiredType.class,
                schemas.cve.v5.imports.cvss.CvssV31.ModifiedScopeType.class,
                schemas.cve.v5.imports.cvss.CvssV31.ModifiedUserInteractionType.class,
                schemas.cve.v5.imports.cvss.CvssV31.PrivilegesRequiredType.class,
                schemas.cve.v5.imports.cvss.CvssV31.RemediationLevelType.class,
                schemas.cve.v5.imports.cvss.CvssV31.ScopeType.class,
                schemas.cve.v5.imports.cvss.CvssV31.SeverityType.class,
                schemas.cve.v5.imports.cvss.CvssV31.UserInteractionType.class,
                schemas.cve.v5.imports.cvss.CvssV31.Version.class,
                AdpTags.class,
                CnaTags.class,
                ReferenceTags.class,
        })
public class ReflectionConfiguration {
}
